name: Daily Website Login

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install puppeteer

    - name: Install Puppeteer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libx11-6 libxcomposite1 libxcursor1 libxdamage1 libxext6 \
          libxfixes3 libxi6 libxtst6 libnss3 libglib2.0-0 libgtk-3-0t64 \
          libasound2t64 libxrandr2 libpangocairo-1.0-0 libatk1.0-0 \
          libatk-bridge2.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 \
          libgdk-pixbuf2.0-0

    - name: Run login script
      id: login-step  # 添加 ID 以便后续引用
      run: node login.js
      env:
        WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        USERNAME_SELECTOR: ${{ secrets.USERNAME_SELECTOR }}
        PASSWORD_SELECTOR: ${{ secrets.PASSWORD_SELECTOR }}
        SUBMIT_SELECTOR: ${{ secrets.SUBMIT_SELECTOR }}
      continue-on-error: true  # 即使失败也继续上传

    - name: Upload failure screenshot as Artifact
      if: always()  # 总是运行，无论成功或失败
      uses: actions/upload-artifact@v4
      with:
        name: login-debug
        path: login-failure.png  # 脚本生成的截屏路径
        retention-days: 7  # 保留 7 天
